server:
  port:8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_service?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

jwt:
  expiration: 2592000  #30 day = 30 * 24 * 60 * 60
  secretKey: O4394zGjSD+N89CCcmec69mHTP206UonQ/09W6JZKrk=
api:
  prefix: api/v1